
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

require("modules.monitors")
require("modules.keybinds")
require("modules.autostart")
require("modules.env")
require("modules.permissions")
require("modules.decorations")
require("modules.rules")
require("modules.layout")
require("modules.misc")
require("modules.input")

-- For Noctalia Color templates
-- Guarded: noctalia.lua is generated by Noctalia at runtime. On a very first
-- boot (or if generation hasn't run yet) the file may not exist - a hard
-- require would make Hyprland fail to start at all.
local noctalia_ok, noctalia = pcall(require, "noctalia")
if noctalia_ok then noctalia.apply_theme() end
